# Data retriaval from IMF data
Data is downloaded manually in excel format. After downlaoded files are converted from xls to xlsx format.

Data is saved in CSV format, where columns are 'Country or Area', 'Item', 'Year', 'Value'.

https://www.imf.org/external/datamapper/CG_DEBT_GDP@GDD/OEMDC/ADVEC/WEOWORLD

https://www.imf.org/external/datamapper/NGDP_RPCH@WEO/OEMDC/ADVEC/WEOWORLD

In [10]:
import pandas as pd
import numpy as np

def extract_from_xlsx(name):
    df = pd.read_excel(name)
    data_name = df.columns[0]
    df=df.rename(columns={data_name:'Country or Area'})
    df2=pd.DataFrame()
    for col in df.columns:
        if col!='Country or Area' and col>2016:
            a=df[['Country or Area',col]].copy()
            a['Year']=col
            a['Item']=data_name
            a=a.rename(columns={col:'Value'}).dropna(subset = ['Country or Area'])
            df2=df2.append(a)
    return df2

In [13]:
df=extract_from_xlsx('imf_rawdata/imf_debt.xlsx')
df=df.append(extract_from_xlsx('imf_rawdata/imf_gdp_growth.xlsx'))
df.to_csv('IMF_statistics.csv', index=False)
pd.DataFrame(df['Country or Area'].unique()).to_csv('Countries.csv', index=False)
print(len(df['Country or Area'].unique()))
df.head(20)

228

,Country or Area,Value,Year,Item
1,Afghanistan,7.99766,2017,Central Government Debt (Percent of GDP)
2,Albania,70.118725,2017,Central Government Debt (Percent of GDP)
3,Algeria,27.259228,2017,Central Government Debt (Percent of GDP)
4,Angola,69.264947,2017,Central Government Debt (Percent of GDP)
5,Antigua and Barbuda,92.322144,2017,Central Government Debt (Percent of GDP)
6,Argentina,57.027842,2017,Central Government Debt (Percent of GDP)
7,Armenia,53.704434,2017,Central Government Debt (Percent of GDP)
8,Australia,32.26376,2017,Central Government Debt (Percent of GDP)
9,Austria,57.046286,2017,Central Government Debt (Percent of GDP)
10,Azerbaijan,22.508608,2017,Central Government Debt (Percent of GDP)
11,"Bahamas, The",52.37688,2017,Central Government Debt (Percent of GDP)
12,Bahrain,88.138294,2017,Central Government Debt (Percent of GDP)
13,Bangladesh,33.376308,2017,Central Government Debt (Percent of GDP)
14,Barbados,159.12634,2017,Central Government Debt (Percent of GDP)
15,Belarus,47.214587,2017,Central Government Debt (Percent of GDP)
16,Belgium,86.807024,2017,Central Government Debt (Percent of GDP)
17,Belize,104.39668,2017,Central Government Debt (Percent of GDP)
18,Benin,39.598463,2017,Central Government Debt (Percent of GDP)
19,Bhutan,111.72426,2017,Central Government Debt (Percent of GDP)
20,Bolivia,32.872792,2017,Central Government Debt (Percent of GDP)